# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 591c1833e390e3d35bb7edfd7aced005a0ace9bd73b4e04db2290990fdd8ccbb64f3fedfffc4840176189297279cf802ebb9a48bc1db3b297fa0333a49c47d9e

test:
  secret_key_base: 0e4cb2876e0fe7e11abebfa13ed7c3d36d93fb56dd8a57e0d8596bd623f5436944ee09b1cf3ef19b173b154be8f9b06b9a7e0773773bf0d7236d329210bd1eaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
